version: '3.8'
services:
  db:
    image: postgres
    ports:
      - 8080:5432
    environment:
      - POSTGRES_PORT=8080
      - POSTGRES_DB=springbootdb
      - POSTGRES_USER=user_dev
      - POSTGRES_PASSWORD=1234
  backend:
    build: ./ShopsServicesProximity_Backend
    volumes:
      - ./ShopsServicesProximity_Backend:/app
    ports:
      - 8000:8085
    command: java -jar target/spring-mvc-rest-0.0.1-SNAPSHOT.jar